swagger: '2.0'
definitions:
  User:
    type: object
    required: 
      - id
      - email
      - first_name
      - last_name
      - profile
    properties:
      id:
        type: integer
        format: int64
        minimum: 1
      email:
        type: string
        format: email
        x-faker: email
      first_name:
        type: string
        x-faker: firstName
      last_name:
        type: string
        x-faker: lastName
      status:
        type: integer
        format: int32
        enum: [10, 20, 30]
      created_at:
        type: integer
        format: int64
        minimum: 1500015000
        maximum: 1550015500
      updated_at:
        type: integer
        format: int64
        minimum: 1500015000
        maximum: 1550015500
      profile:
        $ref: "#/definitions/UserProfile"
    example:
      id: 1
      email: johndoe@domain.com
      first_name: John
      last_name: Doe
      status: 10
      created_at: 1524218003
      updated_at: 1524212345
      profile:
        id: 2
        user_id: 1
        gender: male
        birthday: 23002
        company: "Mafia Corp."
        created_at: 1524218003
        updated_at: 1524212345
  
  UserProfile:
    type: object
    required: 
      - user_id
      - gender
      - birthday
    properties:
      id:
        type: integer
        format: int64
        minimum: 1
      user_id:
        type: integer
        format: int64
        minimum: 1
      gender:
        type: string
        enum: [male, female]
      birthday:
        type: integer
        format: int64
        maximum: 1001001001
        minimum: 0
      company:
        type: string
        x-faker: company
      about:
        type: string
        x-faker: words
        x-faker-config:
          - 5
          - 1
      created_at:
        type: integer
        format: int64
        minimum: 1500015000
        maximum: 1550015500
      updated_at:
        type: integer
        format: int64
        minimum: 1500015000
        maximum: 1550015500
    example:
      id: 2
      user_id: 1
      gender: male
      birthday: 23002
      company: "Mafia Corp."
      created_at: 1524218003
      updated_at: 1524212345