swagger: '2.0'
info:
  version: '1.0'
  title: API Specification
  description: This is API specification starter template.
  
host: my-domain.com
basePath: /api
securityDefinitions:
  bearerAuth:
    type: apiKey
    name: Authorization
    description: |
      For Authorization Bearer Auth format is in use:
      >  Authorization: Bearer {api_token}
      
      _* to authorize with Swagger UI set value as \"Bearer {your_token}\"_
    in: header
schemes:
- http
consumes:
- application/x-www-form-urlencoded
produces:
- application/json

externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"

paths:
  /auth/sign-in:
    $ref: "routes/auth.yaml#/paths/login"
  /auth/verify:
    $ref: "routes/auth.yaml#/paths/verify"
  /auth/password-reset:
    $ref: "routes/auth.yaml#/paths/resetPassword"
  /auth/password-token-verify:
    $ref: "routes/auth.yaml#/paths/verifyResetToken"
  /auth/password-update:
    $ref: "routes/auth.yaml#/paths/updatePassword"

  /users:
    $ref: "routes/users.yaml#/paths/users"
  /users/{user_id}:
    $ref: "routes/users.yaml#/paths/user"

definitions:
  User:
    $ref: "models.yaml#/definitions/User"
