openapi: "3.0.0"
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        email:
          type: string
        auth_key:
          type: string
        first_name:
          type: string
        last_name:
          type: string
        status:
          type: integer
          format: int32
        created_at:
          type: integer
          format: int64
        updated_at:
          type: integer
          format: int64
        profile:
          $ref: "#/components/schemas/UserProfile"
      example:
        id: 1
        email: johndoe@domain.com
        auth_key: adskfjkdsahfiqu4y583240jhasfsdk
        first_name: John
        last_name: Doe
        status: 10
        created_at: 1524218003
        updated_at: 1524212345
        profile:
          id: 2
          user_id: 1
          gender: male
          birthday: 23002
          company: "Mafia Corp."
          created_at: 1524218003
          updated_at: 1524212345
    
    UserProfile:
      type: object
      properties:
        id:
          type: integer
          format: int64
        user_id:
          type: integer
          format: int64
        gender:
          type: string
        birthday:
          type: integer
          format: int64
        company:
          type: string
        created_at:
          type: integer
          format: int64
        updated_at:
          type: integer
          format: int64
      example:
        id: 2
        user_id: 1
        gender: male
        birthday: 23002
        company: "Mafia Corp."
        created_at: 1524218003
        updated_at: 1524212345