swagger: '2.0'
definitions:
  UserModelDraft:
    type: object
    required:
      - email
      - first_name
      - last_name
      - gender
      - birthday
    properties:
      email:
        type: string
        format: email
        x-faker: email
      first_name:
        type: string
        x-faker: firstName
      last_name:
        type: string
        x-faker: lastName
      gender:
        type: string
        enum: [male, female]
      birthday:
        type: integer
        maximum: 1001001001
        minimum: 0
        description: timestamp
      company:
        type: string
        x-faker: company
      about:
        type: string
        x-faker: words
        x-faker-config:
          - 5
          - 1
  UserModel:
    allOf:
      - $ref: '#/definitions/UserModelDraft'
      - type: object
        required:
          - id
        properties:
          id:
            type: integer
            minimum: 1
            example: 23
          status:
            type: integer
            format: int32
            enum: [10, 20, 30]
          created_at:
            type: integer
            format: int64
            minimum: 1500015000
            maximum: 1550015500
          updated_at:
            type: integer
            format: int64
            minimum: 1500015000
            maximum: 1550015500
  UserResource:           
    type: object
    required: 
      - type
      - id
      - attributes
    properties:
      type:
        type: string
        default: user
      id:
        type: integer
        minimum: 1
        example: 23
      attributes:
        $ref: '#/definitions/UserModel'
    example:
      type: user
      id: 23
      attributes:
        id: 23
        email: johndoe@domain.com
        first_name: John
        last_name: Doe
        status: 10
        gender: male
        birthday: 23002
        company: "Mafia Corp."
        created_at: 1524218003
        updated_at: 1524212345
